// <auto-generated />
namespace NewPizza.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class siparisDetay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(siparisDetay));
        
        string IMigrationMetadata.Id
        {
            get { return "201705162010077_siparisDetay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
